id: AA774796E
title: A Brief Prayer for Summoning Prosperity
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:35:29.095920
  last_modified_at: 2022-03-01 06:35:29.095926
