id: AA774796E
title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:35:29.112064
  last_modified_at: 2022-03-01 06:35:29.112067
