id: AA774796E
title: Sang Offering to Yellow Jambhala
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:35:29.104390
  last_modified_at: 2022-03-01 06:35:29.104396
