id: AA774796E
title: Great Clouds of First-Portion Offerings for Prosperity
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:35:29.102202
  last_modified_at: 2022-03-01 06:35:29.102230
